/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCompetenciasRouteImport } from './routes/_authenticated/competencias'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as PainelTokenRouteImport } from './routes/painel.$token'
import { Route as UploadTokenRouteImport } from './routes/upload.$token'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as AuthenticatedEmpresasIndexRouteImport } from './routes/_authenticated/empresas.index'
import { Route as AuthenticatedEmpresasIdRouteRouteImport } from './routes/_authenticated/empresas.$id/route'
import { Route as AuthenticatedEmpresasNovaRouteImport } from './routes/_authenticated/empresas.nova'
import { Route as ApiPublicConviteInfoRouteImport } from './routes/api/public/convite-info'
import { Route as ApiPublicPainelInfoRouteImport } from './routes/api/public/painel-info'
import { Route as ApiPublicUploadRouteImport } from './routes/api/public/upload'
import { Route as ApiPublicUploadInfoRouteImport } from './routes/api/public/upload-info'
import { Route as AuthenticatedEmpresasIdIndexRouteImport } from './routes/_authenticated/empresas.$id/index'
import { Route as AuthenticatedEmpresasIdCompetenciasRouteImport } from './routes/_authenticated/empresas.$id/competencias'
import { Route as AuthenticatedEmpresasIdConciliacaoRouteImport } from './routes/_authenticated/empresas.$id/conciliacao'
import { Route as AuthenticatedEmpresasIdConfiguracoesRouteImport } from './routes/_authenticated/empresas.$id/configuracoes'
import { Route as AuthenticatedEmpresasIdDocumentosRouteImport } from './routes/_authenticated/empresas.$id/documentos'
import { Route as AuthenticatedEmpresasIdGerenciarRouteImport } from './routes/_authenticated/empresas.$id/gerenciar'
import { Route as AuthenticatedEmpresasIdRelatoriosRouteImport } from './routes/_authenticated/empresas.$id/relatorios'
import { Route as AuthenticatedEmpresasIdClientesIndexRouteImport } from './routes/_authenticated/empresas.$id/clientes.index'
import { Route as AuthenticatedEmpresasIdClientesClienteIdRouteImport } from './routes/_authenticated/empresas.$id/clientes.$clienteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompetenciasRoute =
  AuthenticatedCompetenciasRouteImport.update({
    id: '/competencias',
    path: '/competencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelTokenRoute = PainelTokenRouteImport.update({
  id: '/painel/$token',
  path: '/painel/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadTokenRoute = UploadTokenRouteImport.update({
  id: '/upload/$token',
  path: '/upload/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasIndexRoute =
  AuthenticatedEmpresasIndexRouteImport.update({
    id: '/empresas/',
    path: '/empresas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresasIdRouteRoute =
  AuthenticatedEmpresasIdRouteRouteImport.update({
    id: '/empresas/$id',
    path: '/empresas/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresasNovaRoute =
  AuthenticatedEmpresasNovaRouteImport.update({
    id: '/empresas/nova',
    path: '/empresas/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicConviteInfoRoute = ApiPublicConviteInfoRouteImport.update({
  id: '/api/public/convite-info',
  path: '/api/public/convite-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPainelInfoRoute = ApiPublicPainelInfoRouteImport.update({
  id: '/api/public/painel-info',
  path: '/api/public/painel-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadRoute = ApiPublicUploadRouteImport.update({
  id: '/api/public/upload',
  path: '/api/public/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadInfoRoute = ApiPublicUploadInfoRouteImport.update({
  id: '/api/public/upload-info',
  path: '/api/public/upload-info',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEmpresasIdIndexRoute =
  AuthenticatedEmpresasIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmpresasIdRouteRoute,
  } as any)
const AuthenticatedEmpresasIdCompetenciasRoute =
  AuthenticatedEmpresasIdCompetenciasRouteImport.update({
    id: '/competencias',
    path: '/competencias',
    getParentRoute: () => AuthenticatedEmpresasIdRouteRoute,
  } as any)
const AuthenticatedEmpresasIdConciliacaoRoute =
  AuthenticatedEmpresasIdConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedEmpresasIdRouteRoute,
  } as any)
const AuthenticatedEmpresasIdConfiguracoesRoute =
  AuthenticatedEmpresasIdConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedEmpresasIdRouteRoute,
  } as any)
const AuthenticatedEmpresasIdDocumentosRoute =
  AuthenticatedEmpresasIdDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedEmpresasIdRouteRoute,
  } as any)
const AuthenticatedEmpresasIdGerenciarRoute =
  AuthenticatedEmpresasIdGerenciarRouteImport.update({
    id: '/gerenciar',
    path: '/gerenciar',
    getParentRoute: () => AuthenticatedEmpresasIdRouteRoute,
  } as any)
const AuthenticatedEmpresasIdRelatoriosRoute =
  AuthenticatedEmpresasIdRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedEmpresasIdRouteRoute,
  } as any)
const AuthenticatedEmpresasIdClientesIndexRoute =
  AuthenticatedEmpresasIdClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedEmpresasIdRouteRoute,
  } as any)
const AuthenticatedEmpresasIdClientesClienteIdRoute =
  AuthenticatedEmpresasIdClientesClienteIdRouteImport.update({
    id: '/clientes/$clienteId',
    path: '/clientes/$clienteId',
    getParentRoute: () => AuthenticatedEmpresasIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/competencias': typeof AuthenticatedCompetenciasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/painel/$token': typeof PainelTokenRoute
  '/upload/$token': typeof UploadTokenRoute
  '/empresas/$id': typeof AuthenticatedEmpresasIdRouteRouteWithChildren
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/empresas/nova': typeof AuthenticatedEmpresasNovaRoute
  '/api/public/convite-info': typeof ApiPublicConviteInfoRoute
  '/api/public/painel-info': typeof ApiPublicPainelInfoRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/public/upload-info': typeof ApiPublicUploadInfoRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/empresas/': typeof AuthenticatedEmpresasIndexRoute
  '/empresas/$id/competencias': typeof AuthenticatedEmpresasIdCompetenciasRoute
  '/empresas/$id/conciliacao': typeof AuthenticatedEmpresasIdConciliacaoRoute
  '/empresas/$id/configuracoes': typeof AuthenticatedEmpresasIdConfiguracoesRoute
  '/empresas/$id/documentos': typeof AuthenticatedEmpresasIdDocumentosRoute
  '/empresas/$id/gerenciar': typeof AuthenticatedEmpresasIdGerenciarRoute
  '/empresas/$id/relatorios': typeof AuthenticatedEmpresasIdRelatoriosRoute
  '/empresas/$id/': typeof AuthenticatedEmpresasIdIndexRoute
  '/empresas/$id/clientes/$clienteId': typeof AuthenticatedEmpresasIdClientesClienteIdRoute
  '/empresas/$id/clientes/': typeof AuthenticatedEmpresasIdClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/competencias': typeof AuthenticatedCompetenciasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/painel/$token': typeof PainelTokenRoute
  '/upload/$token': typeof UploadTokenRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/empresas/nova': typeof AuthenticatedEmpresasNovaRoute
  '/api/public/convite-info': typeof ApiPublicConviteInfoRoute
  '/api/public/painel-info': typeof ApiPublicPainelInfoRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/public/upload-info': typeof ApiPublicUploadInfoRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/empresas': typeof AuthenticatedEmpresasIndexRoute
  '/empresas/$id/competencias': typeof AuthenticatedEmpresasIdCompetenciasRoute
  '/empresas/$id/conciliacao': typeof AuthenticatedEmpresasIdConciliacaoRoute
  '/empresas/$id/configuracoes': typeof AuthenticatedEmpresasIdConfiguracoesRoute
  '/empresas/$id/documentos': typeof AuthenticatedEmpresasIdDocumentosRoute
  '/empresas/$id/gerenciar': typeof AuthenticatedEmpresasIdGerenciarRoute
  '/empresas/$id/relatorios': typeof AuthenticatedEmpresasIdRelatoriosRoute
  '/empresas/$id': typeof AuthenticatedEmpresasIdIndexRoute
  '/empresas/$id/clientes/$clienteId': typeof AuthenticatedEmpresasIdClientesClienteIdRoute
  '/empresas/$id/clientes': typeof AuthenticatedEmpresasIdClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/competencias': typeof AuthenticatedCompetenciasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/painel/$token': typeof PainelTokenRoute
  '/upload/$token': typeof UploadTokenRoute
  '/_authenticated/empresas/$id': typeof AuthenticatedEmpresasIdRouteRouteWithChildren
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/empresas/nova': typeof AuthenticatedEmpresasNovaRoute
  '/api/public/convite-info': typeof ApiPublicConviteInfoRoute
  '/api/public/painel-info': typeof ApiPublicPainelInfoRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/public/upload-info': typeof ApiPublicUploadInfoRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/empresas/': typeof AuthenticatedEmpresasIndexRoute
  '/_authenticated/empresas/$id/competencias': typeof AuthenticatedEmpresasIdCompetenciasRoute
  '/_authenticated/empresas/$id/conciliacao': typeof AuthenticatedEmpresasIdConciliacaoRoute
  '/_authenticated/empresas/$id/configuracoes': typeof AuthenticatedEmpresasIdConfiguracoesRoute
  '/_authenticated/empresas/$id/documentos': typeof AuthenticatedEmpresasIdDocumentosRoute
  '/_authenticated/empresas/$id/gerenciar': typeof AuthenticatedEmpresasIdGerenciarRoute
  '/_authenticated/empresas/$id/relatorios': typeof AuthenticatedEmpresasIdRelatoriosRoute
  '/_authenticated/empresas/$id/': typeof AuthenticatedEmpresasIdIndexRoute
  '/_authenticated/empresas/$id/clientes/$clienteId': typeof AuthenticatedEmpresasIdClientesClienteIdRoute
  '/_authenticated/empresas/$id/clientes/': typeof AuthenticatedEmpresasIdClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/competencias'
    | '/configuracoes'
    | '/dashboard'
    | '/documentos'
    | '/equipe'
    | '/convite/$token'
    | '/painel/$token'
    | '/upload/$token'
    | '/empresas/$id'
    | '/clientes/$id'
    | '/empresas/nova'
    | '/api/public/convite-info'
    | '/api/public/painel-info'
    | '/api/public/upload'
    | '/api/public/upload-info'
    | '/clientes/'
    | '/empresas/'
    | '/empresas/$id/competencias'
    | '/empresas/$id/conciliacao'
    | '/empresas/$id/configuracoes'
    | '/empresas/$id/documentos'
    | '/empresas/$id/gerenciar'
    | '/empresas/$id/relatorios'
    | '/empresas/$id/'
    | '/empresas/$id/clientes/$clienteId'
    | '/empresas/$id/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/competencias'
    | '/configuracoes'
    | '/dashboard'
    | '/documentos'
    | '/equipe'
    | '/convite/$token'
    | '/painel/$token'
    | '/upload/$token'
    | '/clientes/$id'
    | '/empresas/nova'
    | '/api/public/convite-info'
    | '/api/public/painel-info'
    | '/api/public/upload'
    | '/api/public/upload-info'
    | '/clientes'
    | '/empresas'
    | '/empresas/$id/competencias'
    | '/empresas/$id/conciliacao'
    | '/empresas/$id/configuracoes'
    | '/empresas/$id/documentos'
    | '/empresas/$id/gerenciar'
    | '/empresas/$id/relatorios'
    | '/empresas/$id'
    | '/empresas/$id/clientes/$clienteId'
    | '/empresas/$id/clientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/competencias'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/equipe'
    | '/convite/$token'
    | '/painel/$token'
    | '/upload/$token'
    | '/_authenticated/empresas/$id'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/empresas/nova'
    | '/api/public/convite-info'
    | '/api/public/painel-info'
    | '/api/public/upload'
    | '/api/public/upload-info'
    | '/_authenticated/clientes/'
    | '/_authenticated/empresas/'
    | '/_authenticated/empresas/$id/competencias'
    | '/_authenticated/empresas/$id/conciliacao'
    | '/_authenticated/empresas/$id/configuracoes'
    | '/_authenticated/empresas/$id/documentos'
    | '/_authenticated/empresas/$id/gerenciar'
    | '/_authenticated/empresas/$id/relatorios'
    | '/_authenticated/empresas/$id/'
    | '/_authenticated/empresas/$id/clientes/$clienteId'
    | '/_authenticated/empresas/$id/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  PainelTokenRoute: typeof PainelTokenRoute
  UploadTokenRoute: typeof UploadTokenRoute
  ApiPublicConviteInfoRoute: typeof ApiPublicConviteInfoRoute
  ApiPublicPainelInfoRoute: typeof ApiPublicPainelInfoRoute
  ApiPublicUploadRoute: typeof ApiPublicUploadRoute
  ApiPublicUploadInfoRoute: typeof ApiPublicUploadInfoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/competencias': {
      id: '/_authenticated/competencias'
      path: '/competencias'
      fullPath: '/competencias'
      preLoaderRoute: typeof AuthenticatedCompetenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/$token': {
      id: '/painel/$token'
      path: '/painel/$token'
      fullPath: '/painel/$token'
      preLoaderRoute: typeof PainelTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/$token': {
      id: '/upload/$token'
      path: '/upload/$token'
      fullPath: '/upload/$token'
      preLoaderRoute: typeof UploadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas/': {
      id: '/_authenticated/empresas/'
      path: '/empresas'
      fullPath: '/empresas/'
      preLoaderRoute: typeof AuthenticatedEmpresasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas/$id': {
      id: '/_authenticated/empresas/$id'
      path: '/empresas/$id'
      fullPath: '/empresas/$id'
      preLoaderRoute: typeof AuthenticatedEmpresasIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas/nova': {
      id: '/_authenticated/empresas/nova'
      path: '/empresas/nova'
      fullPath: '/empresas/nova'
      preLoaderRoute: typeof AuthenticatedEmpresasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/convite-info': {
      id: '/api/public/convite-info'
      path: '/api/public/convite-info'
      fullPath: '/api/public/convite-info'
      preLoaderRoute: typeof ApiPublicConviteInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/painel-info': {
      id: '/api/public/painel-info'
      path: '/api/public/painel-info'
      fullPath: '/api/public/painel-info'
      preLoaderRoute: typeof ApiPublicPainelInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload': {
      id: '/api/public/upload'
      path: '/api/public/upload'
      fullPath: '/api/public/upload'
      preLoaderRoute: typeof ApiPublicUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload-info': {
      id: '/api/public/upload-info'
      path: '/api/public/upload-info'
      fullPath: '/api/public/upload-info'
      preLoaderRoute: typeof ApiPublicUploadInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/empresas/$id/': {
      id: '/_authenticated/empresas/$id/'
      path: '/'
      fullPath: '/empresas/$id/'
      preLoaderRoute: typeof AuthenticatedEmpresasIdIndexRouteImport
      parentRoute: typeof AuthenticatedEmpresasIdRouteRoute
    }
    '/_authenticated/empresas/$id/competencias': {
      id: '/_authenticated/empresas/$id/competencias'
      path: '/competencias'
      fullPath: '/empresas/$id/competencias'
      preLoaderRoute: typeof AuthenticatedEmpresasIdCompetenciasRouteImport
      parentRoute: typeof AuthenticatedEmpresasIdRouteRoute
    }
    '/_authenticated/empresas/$id/conciliacao': {
      id: '/_authenticated/empresas/$id/conciliacao'
      path: '/conciliacao'
      fullPath: '/empresas/$id/conciliacao'
      preLoaderRoute: typeof AuthenticatedEmpresasIdConciliacaoRouteImport
      parentRoute: typeof AuthenticatedEmpresasIdRouteRoute
    }
    '/_authenticated/empresas/$id/configuracoes': {
      id: '/_authenticated/empresas/$id/configuracoes'
      path: '/configuracoes'
      fullPath: '/empresas/$id/configuracoes'
      preLoaderRoute: typeof AuthenticatedEmpresasIdConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedEmpresasIdRouteRoute
    }
    '/_authenticated/empresas/$id/documentos': {
      id: '/_authenticated/empresas/$id/documentos'
      path: '/documentos'
      fullPath: '/empresas/$id/documentos'
      preLoaderRoute: typeof AuthenticatedEmpresasIdDocumentosRouteImport
      parentRoute: typeof AuthenticatedEmpresasIdRouteRoute
    }
    '/_authenticated/empresas/$id/gerenciar': {
      id: '/_authenticated/empresas/$id/gerenciar'
      path: '/gerenciar'
      fullPath: '/empresas/$id/gerenciar'
      preLoaderRoute: typeof AuthenticatedEmpresasIdGerenciarRouteImport
      parentRoute: typeof AuthenticatedEmpresasIdRouteRoute
    }
    '/_authenticated/empresas/$id/relatorios': {
      id: '/_authenticated/empresas/$id/relatorios'
      path: '/relatorios'
      fullPath: '/empresas/$id/relatorios'
      preLoaderRoute: typeof AuthenticatedEmpresasIdRelatoriosRouteImport
      parentRoute: typeof AuthenticatedEmpresasIdRouteRoute
    }
    '/_authenticated/empresas/$id/clientes/': {
      id: '/_authenticated/empresas/$id/clientes/'
      path: '/clientes'
      fullPath: '/empresas/$id/clientes/'
      preLoaderRoute: typeof AuthenticatedEmpresasIdClientesIndexRouteImport
      parentRoute: typeof AuthenticatedEmpresasIdRouteRoute
    }
    '/_authenticated/empresas/$id/clientes/$clienteId': {
      id: '/_authenticated/empresas/$id/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/empresas/$id/clientes/$clienteId'
      preLoaderRoute: typeof AuthenticatedEmpresasIdClientesClienteIdRouteImport
      parentRoute: typeof AuthenticatedEmpresasIdRouteRoute
    }
  }
}

interface AuthenticatedEmpresasIdRouteRouteChildren {
  AuthenticatedEmpresasIdCompetenciasRoute: typeof AuthenticatedEmpresasIdCompetenciasRoute
  AuthenticatedEmpresasIdConciliacaoRoute: typeof AuthenticatedEmpresasIdConciliacaoRoute
  AuthenticatedEmpresasIdConfiguracoesRoute: typeof AuthenticatedEmpresasIdConfiguracoesRoute
  AuthenticatedEmpresasIdDocumentosRoute: typeof AuthenticatedEmpresasIdDocumentosRoute
  AuthenticatedEmpresasIdGerenciarRoute: typeof AuthenticatedEmpresasIdGerenciarRoute
  AuthenticatedEmpresasIdRelatoriosRoute: typeof AuthenticatedEmpresasIdRelatoriosRoute
  AuthenticatedEmpresasIdIndexRoute: typeof AuthenticatedEmpresasIdIndexRoute
  AuthenticatedEmpresasIdClientesClienteIdRoute: typeof AuthenticatedEmpresasIdClientesClienteIdRoute
  AuthenticatedEmpresasIdClientesIndexRoute: typeof AuthenticatedEmpresasIdClientesIndexRoute
}

const AuthenticatedEmpresasIdRouteRouteChildren: AuthenticatedEmpresasIdRouteRouteChildren =
  {
    AuthenticatedEmpresasIdCompetenciasRoute:
      AuthenticatedEmpresasIdCompetenciasRoute,
    AuthenticatedEmpresasIdConciliacaoRoute:
      AuthenticatedEmpresasIdConciliacaoRoute,
    AuthenticatedEmpresasIdConfiguracoesRoute:
      AuthenticatedEmpresasIdConfiguracoesRoute,
    AuthenticatedEmpresasIdDocumentosRoute:
      AuthenticatedEmpresasIdDocumentosRoute,
    AuthenticatedEmpresasIdGerenciarRoute:
      AuthenticatedEmpresasIdGerenciarRoute,
    AuthenticatedEmpresasIdRelatoriosRoute:
      AuthenticatedEmpresasIdRelatoriosRoute,
    AuthenticatedEmpresasIdIndexRoute: AuthenticatedEmpresasIdIndexRoute,
    AuthenticatedEmpresasIdClientesClienteIdRoute:
      AuthenticatedEmpresasIdClientesClienteIdRoute,
    AuthenticatedEmpresasIdClientesIndexRoute:
      AuthenticatedEmpresasIdClientesIndexRoute,
  }

const AuthenticatedEmpresasIdRouteRouteWithChildren =
  AuthenticatedEmpresasIdRouteRoute._addFileChildren(
    AuthenticatedEmpresasIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCompetenciasRoute: typeof AuthenticatedCompetenciasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedEmpresasIdRouteRoute: typeof AuthenticatedEmpresasIdRouteRouteWithChildren
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedEmpresasNovaRoute: typeof AuthenticatedEmpresasNovaRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedEmpresasIndexRoute: typeof AuthenticatedEmpresasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCompetenciasRoute: AuthenticatedCompetenciasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedEmpresasIdRouteRoute:
    AuthenticatedEmpresasIdRouteRouteWithChildren,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedEmpresasNovaRoute: AuthenticatedEmpresasNovaRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedEmpresasIndexRoute: AuthenticatedEmpresasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  PainelTokenRoute: PainelTokenRoute,
  UploadTokenRoute: UploadTokenRoute,
  ApiPublicConviteInfoRoute: ApiPublicConviteInfoRoute,
  ApiPublicPainelInfoRoute: ApiPublicPainelInfoRoute,
  ApiPublicUploadRoute: ApiPublicUploadRoute,
  ApiPublicUploadInfoRoute: ApiPublicUploadInfoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
