/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCompetenciasRouteImport } from './routes/_authenticated/competencias'
import { Route as AuthenticatedConciliacaoRouteImport } from './routes/_authenticated/conciliacao'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedEmpresaRouteImport } from './routes/_authenticated/empresa'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as ApiAssistenteRouteImport } from './routes/api/assistente'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as PainelTokenRouteImport } from './routes/painel.$token'
import { Route as UploadTokenRouteImport } from './routes/upload.$token'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedClientesClienteIdRouteImport } from './routes/_authenticated/clientes.$clienteId'
import { Route as ApiPublicConviteInfoRouteImport } from './routes/api/public/convite-info'
import { Route as ApiPublicPainelInfoRouteImport } from './routes/api/public/painel-info'
import { Route as ApiPublicUploadRouteImport } from './routes/api/public/upload'
import { Route as ApiPublicUploadInfoRouteImport } from './routes/api/public/upload-info'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompetenciasRoute =
  AuthenticatedCompetenciasRouteImport.update({
    id: '/competencias',
    path: '/competencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConciliacaoRoute =
  AuthenticatedConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresaRoute = AuthenticatedEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAssistenteRoute = ApiAssistenteRouteImport.update({
  id: '/api/assistente',
  path: '/api/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelTokenRoute = PainelTokenRouteImport.update({
  id: '/painel/$token',
  path: '/painel/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadTokenRoute = UploadTokenRouteImport.update({
  id: '/upload/$token',
  path: '/upload/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesClienteIdRoute =
  AuthenticatedClientesClienteIdRouteImport.update({
    id: '/clientes/$clienteId',
    path: '/clientes/$clienteId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicConviteInfoRoute = ApiPublicConviteInfoRouteImport.update({
  id: '/api/public/convite-info',
  path: '/api/public/convite-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPainelInfoRoute = ApiPublicPainelInfoRouteImport.update({
  id: '/api/public/painel-info',
  path: '/api/public/painel-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadRoute = ApiPublicUploadRouteImport.update({
  id: '/api/public/upload',
  path: '/api/public/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadInfoRoute = ApiPublicUploadInfoRouteImport.update({
  id: '/api/public/upload-info',
  path: '/api/public/upload-info',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/competencias': typeof AuthenticatedCompetenciasRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/api/assistente': typeof ApiAssistenteRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/painel/$token': typeof PainelTokenRoute
  '/upload/$token': typeof UploadTokenRoute
  '/clientes/$clienteId': typeof AuthenticatedClientesClienteIdRoute
  '/api/public/convite-info': typeof ApiPublicConviteInfoRoute
  '/api/public/painel-info': typeof ApiPublicPainelInfoRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/public/upload-info': typeof ApiPublicUploadInfoRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/competencias': typeof AuthenticatedCompetenciasRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/api/assistente': typeof ApiAssistenteRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/painel/$token': typeof PainelTokenRoute
  '/upload/$token': typeof UploadTokenRoute
  '/clientes/$clienteId': typeof AuthenticatedClientesClienteIdRoute
  '/api/public/convite-info': typeof ApiPublicConviteInfoRoute
  '/api/public/painel-info': typeof ApiPublicPainelInfoRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/public/upload-info': typeof ApiPublicUploadInfoRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/competencias': typeof AuthenticatedCompetenciasRoute
  '/_authenticated/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/empresa': typeof AuthenticatedEmpresaRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/api/assistente': typeof ApiAssistenteRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/painel/$token': typeof PainelTokenRoute
  '/upload/$token': typeof UploadTokenRoute
  '/_authenticated/clientes/$clienteId': typeof AuthenticatedClientesClienteIdRoute
  '/api/public/convite-info': typeof ApiPublicConviteInfoRoute
  '/api/public/painel-info': typeof ApiPublicPainelInfoRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/public/upload-info': typeof ApiPublicUploadInfoRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/competencias'
    | '/conciliacao'
    | '/configuracoes'
    | '/dashboard'
    | '/documentos'
    | '/empresa'
    | '/equipe'
    | '/relatorios'
    | '/api/assistente'
    | '/convite/$token'
    | '/painel/$token'
    | '/upload/$token'
    | '/clientes/$clienteId'
    | '/api/public/convite-info'
    | '/api/public/painel-info'
    | '/api/public/upload'
    | '/api/public/upload-info'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/competencias'
    | '/conciliacao'
    | '/configuracoes'
    | '/dashboard'
    | '/documentos'
    | '/empresa'
    | '/equipe'
    | '/relatorios'
    | '/api/assistente'
    | '/convite/$token'
    | '/painel/$token'
    | '/upload/$token'
    | '/clientes/$clienteId'
    | '/api/public/convite-info'
    | '/api/public/painel-info'
    | '/api/public/upload'
    | '/api/public/upload-info'
    | '/clientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/competencias'
    | '/_authenticated/conciliacao'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/empresa'
    | '/_authenticated/equipe'
    | '/_authenticated/relatorios'
    | '/api/assistente'
    | '/convite/$token'
    | '/painel/$token'
    | '/upload/$token'
    | '/_authenticated/clientes/$clienteId'
    | '/api/public/convite-info'
    | '/api/public/painel-info'
    | '/api/public/upload'
    | '/api/public/upload-info'
    | '/_authenticated/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAssistenteRoute: typeof ApiAssistenteRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  PainelTokenRoute: typeof PainelTokenRoute
  UploadTokenRoute: typeof UploadTokenRoute
  ApiPublicConviteInfoRoute: typeof ApiPublicConviteInfoRoute
  ApiPublicPainelInfoRoute: typeof ApiPublicPainelInfoRoute
  ApiPublicUploadRoute: typeof ApiPublicUploadRoute
  ApiPublicUploadInfoRoute: typeof ApiPublicUploadInfoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/competencias': {
      id: '/_authenticated/competencias'
      path: '/competencias'
      fullPath: '/competencias'
      preLoaderRoute: typeof AuthenticatedCompetenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conciliacao': {
      id: '/_authenticated/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof AuthenticatedConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa': {
      id: '/_authenticated/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AuthenticatedEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/assistente': {
      id: '/api/assistente'
      path: '/api/assistente'
      fullPath: '/api/assistente'
      preLoaderRoute: typeof ApiAssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/$token': {
      id: '/painel/$token'
      path: '/painel/$token'
      fullPath: '/painel/$token'
      preLoaderRoute: typeof PainelTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/$token': {
      id: '/upload/$token'
      path: '/upload/$token'
      fullPath: '/upload/$token'
      preLoaderRoute: typeof UploadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$clienteId': {
      id: '/_authenticated/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof AuthenticatedClientesClienteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/convite-info': {
      id: '/api/public/convite-info'
      path: '/api/public/convite-info'
      fullPath: '/api/public/convite-info'
      preLoaderRoute: typeof ApiPublicConviteInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/painel-info': {
      id: '/api/public/painel-info'
      path: '/api/public/painel-info'
      fullPath: '/api/public/painel-info'
      preLoaderRoute: typeof ApiPublicPainelInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload': {
      id: '/api/public/upload'
      path: '/api/public/upload'
      fullPath: '/api/public/upload'
      preLoaderRoute: typeof ApiPublicUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload-info': {
      id: '/api/public/upload-info'
      path: '/api/public/upload-info'
      fullPath: '/api/public/upload-info'
      preLoaderRoute: typeof ApiPublicUploadInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCompetenciasRoute: typeof AuthenticatedCompetenciasRoute
  AuthenticatedConciliacaoRoute: typeof AuthenticatedConciliacaoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEmpresaRoute: typeof AuthenticatedEmpresaRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedClientesClienteIdRoute: typeof AuthenticatedClientesClienteIdRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCompetenciasRoute: AuthenticatedCompetenciasRoute,
  AuthenticatedConciliacaoRoute: AuthenticatedConciliacaoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEmpresaRoute: AuthenticatedEmpresaRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedClientesClienteIdRoute: AuthenticatedClientesClienteIdRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAssistenteRoute: ApiAssistenteRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  PainelTokenRoute: PainelTokenRoute,
  UploadTokenRoute: UploadTokenRoute,
  ApiPublicConviteInfoRoute: ApiPublicConviteInfoRoute,
  ApiPublicPainelInfoRoute: ApiPublicPainelInfoRoute,
  ApiPublicUploadRoute: ApiPublicUploadRoute,
  ApiPublicUploadInfoRoute: ApiPublicUploadInfoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
